[project]
name = "untitled-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
